### ISSUE TITLE
More pythonic interface (os.walk, file objects)

### ISSUE THREAD

**Issue by ptallada** [clalancette/pycdlib#15]
Hi,

First of all, thanks a lot for this module, it has saved me a lot of work!
I wanted to suggest the implementation of more pythonic interfaces, as the current ones are ad-hoc.
It would help this project a lot to have compatible interfaces, as people would be able to use it more easily.

For instance:

- file object interface. Add the possibility of accessing the files in an ISO through a pure file object interface. Current methods only allow writing to a file or to an in-memory stream. This limits the ability to process large files in an streaming way.

- os.walk. Add an alternative to list_children by implementing the walk() method in order to navigate the directory tree.

Thanks again for your work!

**Comment by clalancette** [comment]
> First of all, thanks a lot for this module, it has saved me a lot of work!

Glad you are finding it useful.

> I wanted to suggest the implementation of more pythonic interfaces, as the current ones are ad-hoc.

Yeah, I agree that the actual API isn't the best.  It mostly grew organically as the project did, and in the interest of not breaking users, I've mostly kept it as-is.  I do have some ideas on how to improve it (at least to make it more self-consistent), but that has sort of been on the backburner since I need to figure out backwards compatibility.

>     file object interface. Add the possibility of accessing the files in an ISO through a pure file object interface. Current methods only allow writing to a file or to an in-memory stream. This limits the ability to process large files in an streaming way.

Well, the current methods should allow you to use any file-like object.  But that being said, you are correct in that it is an "all or nothing" style interface.  You can't get the data a little at a time and process it.  I'm not entirely sure what this API would look like, however.  Would you like a context manager?  Something like:

```
with iso.open_file_streaming() as infp:
    data = infp.read(4096)
    while data is not None:
        do_something(data)
        data = infp.read(4096)
```

> 
>     os.walk. Add an alternative to list_children by implementing the walk() method in order to navigate the directory tree.

Ah yeah, that should be easy enough to add.  I never really needed it, so I didn't bother.  I'll put this on the list of things to implement.

**Comment by clalancette** [comment]
I did an initial implementation of `walk` over on this branch: https://github.com/clalancette/pycdlib/tree/os-walk

Right now I have it returning all directory records instead of 'paths' like `os.walk` does.  It is more efficient that way, but makes it a little harder to build up absolute paths.  It is also lightly tested at the moment.  If you have a few minutes to give that branch a whirl, I'd appreciate feedback on what you would like to see from that API.

**Comment by ptallada** [comment]
Hi,

Thanks for taking this into consideration :)

I would propose to stick as much as possible to the official Python API.
For instance, if you need directory records/entries, you can implement scandir() method. Then, os.walk() can use it and return only path names.

https://docs.python.org/3.5/library/os.html#os.walk
https://docs.python.org/3.5/library/os.html#os.scandir

BTW, you can see an implementation of scandir() and walk() in the following link. Developing this should be as easier as replacing the calls to get children entries and names, etc.

https://github.com/benhoyt/scandir/blob/master/scandir.py#L593

As for the file object interface, I would propose that on opening a file for reading, it should return an object that implements some derivative of io.IOBase, at least io.RawIOBase. The bare implementation only needs a readinto() method, but adding the seek() method would also be very helpful.

https://docs.python.org/3/library/io.html#io.RawIOBase

Let me know what do you think about this :)

Thanks again, and I'll try testing your os.walk branch in the next days

**Comment by mikekuku** [comment]
Hi,
 i am also using this module, thanks a lot!! XD, just can not figure out how to copy all the file ISO out easily and i am more than happy that this feature will dropped in. As a newbie of Python then i won't able to provide useful comments at current. if further testing is needed then i can try.
thanks again.

**Comment by mikekuku** [comment]
Hi,
Thanks! I will definitely try that and update the result in here. By using **os-walker** branch then i found out that the folder and the file name is not case sensitive. May i know do your walk function support case sensitive in file name? Following is my sample output (sample from Ubuntu ISO image). I had tried **_printable_name** and **file_ident** fields.

b'== Path == //.DISK/'
File Name : b'MD5SUM.TXT;1'
File Name : b'README.DISKDEFINES;1'
File Name : b'UBUNTU.;1'
....

**Comment by mikekuku** [comment]
Hi,
I have tried  pycdlib-extract-files under **windows** with following command and can extract ISO files from 'boot' folder but when passing the '/' parameter then i got following error.

PS D:\Test> python .\pycdlib-extract-files -path-type joliet -start-path '**/boot'** D:\ubuntu-18.04.1-desktop-amd64.iso

PS D:\Test> python .\pycdlib-extract-files -path-type joliet -start-path '/' D:\ubuntu-18.04.1-desktop-amd64.iso
Opening D:\ubuntu-18.04.1-desktop-amd64.iso
b'/'
Traceback (most recent call last):
  File ".\pycdlib-extract-files", line 107, in <module>
    sys.exit(main())
  File ".\pycdlib-extract-files", line 92, in main
    os.makedirs(relname)
  File "C:\Users\MikeLin\AppData\Local\Programs\Python\Python37-32\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
**PermissionError: [WinError 5] Access is denied**: b'/'
PS D:\Test>

**Comment by clalancette** [comment]
> Thanks! I will definitely try that and update the result in here. By using os-walker branch then i found out that the folder and the file name is not case sensitive. May i know do your walk function support case sensitive in file name?

So, that is actually a limitation of ISO9660 pathnames.  In original ISO9660, only uppercase ASCII letters, numbers, and `_` were allowed.  That's why you are seeing those names.  If you want to see the more "natural" names, try passing `rr_path` or `joliet_path` to the `walk` method.



> I have tried pycdlib-extract-files under windows with following command and can extract ISO files from 'boot' folder but when passing the '/' parameter then i got following error.
> 
> PS D:\Test> python .\pycdlib-extract-files -path-type joliet -start-path '/boot' D:\ubuntu-18.04.1-desktop-amd64.iso

I tried this both on Linux and on Windows, and I don't have this problem.  Given the output, I suspect that what is happening is that you have an older version of `pycdlib` installed.  Unfortunately, there were some bugs (even in 1.6.0) that I had to fix, so it would probably be best if you could re-install pycdlib from source and give it another try.

Thanks for the testing and the feedback!  I may have some additional time this week to polish up the `walk` method, I'll let you know when I do.

**Comment by clalancette** [comment]
I ended up changing the `walk` method to be a lot more like `os.walk`, and writing a bunch of tests for it.  I've now merged that into master, but we can make more changes to it if we want.

The request to make a context-manager for getting file data is still outstanding.  I'll take a look at that one eventually, but I think it is going to be a lot more work so it may take some time to do.

**Comment by clalancette** [comment]
> I just tested a bit the walk method, works beautifully and will be most helpful.

Fantastic, thanks for testing it.

> Having said that, keep in mind that currently the implementation covers only a subset of the full walk() interface. Mainly, it does not take the rest of arguments (topdown, onerror, followlinks), but for me it is enough as it is :)

Yeah, I looked at the other flags and while they could be done, I wasn't sure if you needed them.  Given that the API is kwarg based, it will be easy enough to add them in the future.  For now I'll just leave that as a TODO for someone to do in the future :).

**Comment by clalancette** [comment]
Thank you for these suggestions, I think they have helped improve the API to pycdlib.  I've now addressed all 3 of the concerns originally brought up here (walk, context manager, and a tool to extract files).  Thus, I'm going to close this out.  If you have any other ideas for improvement, please feel free to open a new issue and we can discuss it there.
