### ISSUE TITLE
pycdlib-extract-files throws an exception extracting empty files or symlinks

### ISSUE THREAD

**Issue by clalancette** [clalancette/pycdlib#25]
@amlamarra This is the fourth issue split out of #21 

I did have to modify `pycdlib-extract-files` a bit as it was halting on certain errors, like when it tried extracting empty files or symlinks:
```
Traceback (most recent call last):
  File "./pycdlib-extract-modified.py", line 111, in <module>
    sys.exit(main())
  File "./pycdlib-extract-modified.py", line 102, in main
    iso.get_file_from_iso(os.path.join(args.extract_to, relname), **{pathname: ident_to_here})
  File "/usr/local/lib/python3.5/dist-packages/pycdlib/pycdlib.py", line 4119, in get_file_from_iso
    self._get_file_from_iso_fp(fp, blocksize, iso_path, rr_path, joliet_path)
  File "/usr/local/lib/python3.5/dist-packages/pycdlib/pycdlib.py", line 2632, in _get_file_from_iso_fp
    raise pycdlibexception.PyCdlibInvalidInput('Symlinks have no data associated with them')
pycdlib.pycdlibexception.PyCdlibInvalidInput: Symlinks have no data associated with them
```
I enclosed line 100 in  a try-except statement:
```
 99         else:
100             try:
101                 iso.get_file_from_iso(os.path.join(args.extract_to, relname), **{pathname: ident_to_here})
102             except Exception as ex:
103                 print("ERROR on {}: {}".format(relname, ex.args[0]))
```

**Comment by clalancette** [comment]
Yeah, this is a bug.  I'll take a look at making `pycdlib-extract-files` more robust to this.

**Comment by clalancette** [comment]
OK, try out 6f3777218e9a13d6e0c24e587d8b6e6831e685af , which should fix this issue.  I'm going to close this out, but feel free to comment/reopen if you are still having problems.
