### ISSUE TITLE
Doesn't support UEFI platform ID

### ISSUE THREAD

**Issue by hadess** [clalancette/pycdlib#27]
Not going to claim to be an expert in El Torito here, but it looks like:
```python
import pycdlib
iso = pycdlib.PyCdlib()
# From https://dl.fedoraproject.org/pub/fedora/linux/releases/30/Server/aarch64/iso/
iso.open("Fedora-Server-netinst-aarch64-30-1.2.iso")
```

fails:
```
PYTHONPATH=./ python3 foo.py 
Traceback (most recent call last):
  File "foo.py", line 3, in <module>
    iso.open("/home/hadess/Projects/Fedora/fedora-kickstarts/Fedora-Server-netinst-aarch64-30-1.2.iso")
  File "/home/hadess/Projects/jhbuild/pycdlib/pycdlib/pycdlib.py", line 4051, in open
    self._open_fp(fp)
  File "/home/hadess/Projects/jhbuild/pycdlib/pycdlib/pycdlib.py", line 2411, in _open_fp
    self._check_and_parse_eltorito(br)
  File "/home/hadess/Projects/jhbuild/pycdlib/pycdlib/pycdlib.py", line 1500, in _check_and_parse_eltorito
    while not self.eltorito_boot_catalog.parse(data):
  File "/home/hadess/Projects/jhbuild/pycdlib/pycdlib/eltorito.py", line 658, in parse
    self.validation_entry.parse(valstr)
  File "/home/hadess/Projects/jhbuild/pycdlib/pycdlib/eltorito.py", line 204, in parse
    raise pycdlibexception.PyCdlibInvalidISO('El Torito Validation entry platform ID 0x%X not valid' % (self.platform_id))
pycdlib.pycdlibexception.PyCdlibInvalidISO: El Torito Validation entry platform ID 0xEF not valid
```

when it shouldn't, as 0xEF is the platform ID for UEFI.

**Comment by hadess** [comment]
Reference for the 0xEF value: https://wiki.osdev.org/El-Torito

**Comment by hadess** [comment]
(This is stopping lorax from being able to process a valid installer media)

**Comment by clalancette** [comment]
Ah, I see.  I wrote this code based on the original El Torito specification: https://pdos.csail.mit.edu/6.828/2018/readings/boot-cdrom.pdf .  That only specifies platform IDs of 0x0, 0x1, and 0x2.  I didn't realize that UEFI had added 0xef as a valid platform ID.  I've added support for that in 91c826fa0cbb3bc4ec71bcad21cb4e9ed2882ff0 , along with tests and a fix for the checksum calculation.  Please give it whirl, and if you are still having problems feel free to re-open.

**Comment by hadess** [comment]
That fixed the problem I ran into, thanks.
